### ISSUE TITLE
Hunt down cause of occasional auth failures

### ISSUE THREAD

**Issue by lemccarthy** [dfci/cidc-cli#11]
Maybe one time in 15, the token exchange fails, but cursory investigation has not made it clear why. Need to devote some time to hunting this down.

**Comment by jim-bo** [comment]
```bash
You are not currently authenticated. Launching a page to sign in with google
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/interface/cli.py", line 284, in <module>
    CIDCCLI().cmdloop()
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/interface/cli.py", line 198, in cmdloop
    super(ExitCmd, self).cmdloop(intro="")
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/interface/cli.py", line 222, in onecmd
    response = super(ExitCmd, self).onecmd(line)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/interface/cli.py", line 261, in do_upload_data
    run_upload_process()
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/interface/cli.py", line 92, in run_upload_process
    "This is the upload function\n"
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/utilities/cli_utilities.py", line 219, in select_assay_trial
    eve_token = ensure_logged_in()
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/utilities/cli_utilities.py", line 103, in ensure_logged_in
    eve_token = run_auth_proc()
  File "/Users/jlindsay/Documents/Code/cidc/cidc-cli/auth0/auth0.py", line 167, in run_auth_proc
    serversocket.shutdown(socket.SHUT_WR)
OSError: [Errno 57] Socket is not connected
```

**Comment by jim-bo** [comment]
```bash
(Cmd) upload_data
This is the upload function

You are not currently authenticated. Launching a page to sign in with google
Error exchanging code for token
Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1104630f0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /trials (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104630f0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cidc_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/interface/cli.py", line 286, in main
    CIDCCLI().cmdloop()
  File "/usr/local/lib/python3.6/site-packages/interface/cli.py", line 204, in cmdloop
    super(ExitCmd, self).cmdloop(intro="")
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.6/site-packages/interface/cli.py", line 228, in onecmd
    response = super(ExitCmd, self).onecmd(line)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.6/site-packages/interface/cli.py", line 267, in do_upload_data
    run_upload_process()
  File "/usr/local/lib/python3.6/site-packages/interface/cli.py", line 95, in run_upload_process
    "This is the upload function\n"
  File "/usr/local/lib/python3.6/site-packages/utilities/cli_utilities.py", line 222, in select_assay_trial
    response = EVE_FETCHER.get(token=eve_token, endpoint='trials')
  File "/usr/local/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 104, in get
    return self.do_wrap(requests.get, endpoint=endpoint, code=code, token=token, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 156, in do_wrap
    return wrapped_request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 57, in handle_error
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 154, in wrapped_request
    return request_func(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /trials (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1104630f0>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by jim-bo** [comment]
old so im closing
