### ISSUE TITLE
No user in DB

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#18]
Not sure if the users were dropped when the system was reset?

```bash
(Cmd) download_data
This is the download function

You are not currently authenticated. Launching a page to sign in with google
Request Unsuccesful:
Unauthorized
{'code': 'No_info', 'description': 'No userinfo found at endpoint'}
Traceback (most recent call last):
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/bin/cidc_cli", line 11, in <module>
    sys.exit(main())
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 282, in main
    CIDCCLI().cmdloop()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 200, in cmdloop
    super(ExitCmd, self).cmdloop(intro="")
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 224, in onecmd
    response = super(ExitCmd, self).onecmd(line)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 269, in do_download_data
    run_download_process()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 30, in run_download_process
    selections = select_assay_trial("This is the download function\n")
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/utilities/cli_utilities.py", line 228, in select_assay_trial
    response = EVE_FETCHER.get(token=eve_token, endpoint='trials')
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 104, in get
    return self.do_wrap(requests.get, endpoint=endpoint, code=code, token=token, **kwargs)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 156, in do_wrap
    return wrapped_request(**kwargs)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 65, in handle_error
    raise RuntimeError
RuntimeError
```

**Comment by lemccarthy** [comment]
That's an auth0 error message, it means it can't find info on you at the
userinfo endpoint
