### ISSUE TITLE
must be str

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#20]
I tried to upload files and during authorization I got this error

```bash
Traceback (most recent call last):
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/bin/cidc_cli", line 11, in <module>
    sys.exit(main())
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 282, in main
    CIDCCLI().cmdloop()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 200, in cmdloop
    super(ExitCmd, self).cmdloop(intro="")
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 224, in onecmd
    response = super(ExitCmd, self).onecmd(line)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 263, in do_upload_data
    run_upload_process()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 89, in run_upload_process
    "This is the upload function\n"
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/utilities/cli_utilities.py", line 222, in select_assay_trial
    eve_token = ensure_logged_in()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/utilities/cli_utilities.py", line 103, in ensure_logged_in
    eve_token = run_auth_proc()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/auth0/auth0.py", line 212, in run_auth_proc
    print('OS ERROR: ' + error)
TypeError: must be str, not SSLError
```

**Comment by jim-bo** [comment]
too old
