### ISSUE TITLE
issues with user

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-cli#21]
Attempted to login and got this. jlindsay@bcb-mail.dfci.harvard.edu was the account.

```bash
Welcome to the CIDC CLI Tool
(Cmd) upload_data
This is the upload function

You are not currently authenticated. Launching a page to sign in with google
Request Unsuccesful:
Unauthorized
{'code': 'No_info', 'description': 'No userinfo found at endpoint'}
Traceback (most recent call last):
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/bin/cidc_cli", line 11, in <module>
    sys.exit(main())
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 282, in main
    CIDCCLI().cmdloop()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 200, in cmdloop
    super(ExitCmd, self).cmdloop(intro="")
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 224, in onecmd
    response = super(ExitCmd, self).onecmd(line)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 263, in do_upload_data
    run_upload_process()
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/interface/cli.py", line 89, in run_upload_process
    "This is the upload function\n"
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/utilities/cli_utilities.py", line 228, in select_assay_trial
    response = EVE_FETCHER.get(token=eve_token, endpoint='trials')
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 104, in get
    return self.do_wrap(requests.get, endpoint=endpoint, code=code, token=token, **kwargs)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 156, in do_wrap
    return wrapped_request(**kwargs)
  File "/Users/jlindsay/.local/share/virtualenvs/cidc-cli-USraMjIr/lib/python3.6/site-packages/cidc_utils/requests/SmartFetch.py", line 65, in handle_error
    raise RuntimeError
RuntimeError
```

**Comment by jim-bo** [comment]
Need to write a handler for this scenario as well as find where the issue is.

**Comment by jim-bo** [comment]
@lemccarthy any progress on this one?

**Comment by jim-bo** [comment]
No progress, gonna close :(
